### ISSUE TITLE
tomato invalid memory access

### ISSUE THREAD

**Issue by calkedd** [X-com/RealmShark#13]
when i open the program it doesnt show and dps or chat logs when i open with console it displays this: 
Exception in thread "Thread-16" java.lang.Error: Invalid memory access
        at packets.packetcapture.sniff.ardikars.NativeMappings.pcap_loop(Native Method)
        at packets.packetcapture.sniff.ardikars.NativeBridge.loop(NativeBridge.java:78)
        at packets.packetcapture.sniff.Sniffer$1.run(Sniffer.java:131)
        at java.base/java.lang.Thread.run(Thread.java:1589)

java version:
java version "19.0.1" 2022-10-18
Java(TM) SE Runtime Environment (build 19.0.1+10-21)
Java HotSpot(TM) 64-Bit Server VM (build 19.0.1+10-21, mixed mode, sharing)

**Comment by X-com** [comment]
I would strongly suggest to follow the trouble shoot guide. I believe this problem is solvable following the steps in the guide.

**Comment by calkedd** [comment]
> I would strongly suggest to follow the trouble shoot guide. I believe this problem is solvable following the steps in the guide.

i have tried some of those things and now nothing shows in console but still i dont see anything like chat or dps
